### ISSUE TITLE
Merging with a range causes in-page links to stop working

### ISSUE THREAD

**Issue by vindaddo** [johnwhitington/cpdf-source#140]
Using `cpdf -retain-numbering orig.pdf 1-7,10-352 -o new.pdf` to remove 2 pages from the pdf, all bookmarks/links that point withIN a page (e.g. a link that would normally take user to the bottom of a page), will now only point to the top of the page.

Not sure how to debug, but I did a `cpdf -list-bookmarks` on the before and after:
`$ cpdf -list-bookmarks -utf8  orig.pdf  | grep 'Chapter 1:'
0 "Chapter 1: A Gentle Introduction to Machine Learning" 21  "[21/XYZ null 498.517 null]"`
`$ cpdf -list-bookmarks -utf8  new.pdf  | grep 'Chapter 1:'
0 "Chapter 1: A Gentle Introduction to Machine Learning" 19  "[19/XYZ null 498.517 null]"`

This problem happens when a range is specified, regardless of whether `-retain-numbering` is used, even if all pages are included in the range (1-end).

**Comment by johnwhitington** [comment]
Can you supply the file? I can do without, but it’s easier with...

**Comment by vindaddo** [comment]
It's 33MB, so had to upload to an external site: https://ufile.io/0plk55hn

**Comment by johnwhitington** [comment]
It's more fundamental than merging -- it seems to be a failure to properly round-trip the bookmark positions. For example, if we do:

```
cpdf -list-bookmarks machine_learning_algorithms.pdf > foo
cpdf -add-bookmarks foo machine_learning_algorithms.pdf -o out.pdf
```

we see that out.pdf does not jump to the in-page positions properly.

Are you a commercial customer? If so, I think we can fix this quickly. If not, it will have to wait for the next update.

**Comment by johnwhitington** [comment]
@vindaddo Could you re-supply the file, please? Its hosting period has expired.

I am working on fixing all outstanding bookmarks issues for v2.3 and I would like to make sure this one has been fixed.

**Comment by johnwhitington** [comment]
Bookmarks should now entirely round-trip. Closing this bug now. Reopen if you can resupply the file, please.

**Comment by vindaddo** [comment]
I didn't get pinged earlier and just noticed the new release of 2.3. I tried the above on the original file and the problem still exists, for both my example of using `-retain-numbering` and your round-trip of the bookmark file.

I re-uploaded the file here: https://filebin.ca/4v7Hj9KNltrO/MachineLearningAlgorithms-Packt-2017.pdf

**Comment by johnwhitington** [comment]
I tried this now, doing the range 1-end.

There is no change in the bookmarks. The middle-of-the-page bookmarks seem to work fine in Adobe Reader, but point to the top of the page in Preview.app (but Preview.app works fine on the original file.)

So this needs further investigation.

**Comment by vindaddo** [comment]
I ran `qpdf --qdf --object-streams=disable` on both the input and output pdf files to make a readable dump of the contents and noticed the named destinationsin the original input file had a `0` for the first field of the `/XYZ` key, but in the output file, that field had been converted to a `null` value.

**Comment by johnwhitington** [comment]
I think Preview is wrong here, and Adobe Reader is right, in terms of the actual behaviour on the new bookmarks. The ISO Standard says:

```
[page /XYZ left top zoom]

Display the page designated by page, with the coordinates (left, top) positioned at the upper-left corner of the window and the contents of the page magnified by the factor zoom. A null value for any of the parameters left, top, or zoom specifies that the current value of that parameter shall be retained unchanged. A zoom value of 0 has the same meaning as a null value.
```

However, it's wrong for cpdf to change the value of an existing bookmark from '0' to 'null', of course, since they mean different things.

Working on a fix now.

**Comment by johnwhitington** [comment]
Fixed in the source. New binaries to follow later this week.
